matrix:
  include:
    - os: linux
      dist: focal
      arch:
        - arm64
      compiler: gcc
      addons:
        apt:
          packages:
            - libhts-dev
            - libcurl4-openssl-dev
            - libtabixpp-dev 
            - libtabixpp0
            - python3
            - python3-all-dev
            - pybind11-dev
script:
    - pkg-config --list-all
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build . --verbose
    - ctest --verbose
