name: Vcflib CI
on: [push, pull_request]
jobs:
  arch:
    name: vcflib-CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
    - name: apt update
      run: sudo apt-get -o Acquire::Retries=3 update
    - name: install dependencies
      run: sudo apt-get -o Acquire::Retries=3 install -y -V
        cmake
        libhts-dev
        libtabixpp-dev
        libtabixpp0
        pybind11-dev
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: install zig using wget
      run: |
        wget -q https://ziglang.org/download/0.9.1/zig-linux-x86_64-0.9.1.tar.xz
        tar xf zig-linux-x86_64-0.9.1.tar.xz
        ./zig-linux-x86_64-0.9.1/zig version
        echo "$(pwd)/zig-linux-x86_64-0.9.1" >> $GITHUB_PATH
        echo GITHUB_PATH=$GITHUB_PATH
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Configure
      run: |
        echo "$(pwd)/zig-linux-x86_64-0.9.1" >> $GITHUB_PATH
        mkdir -p build
        cd build
        cmake ..
    - name: Compile
      run: cmake --build build/ --verbose -- -j 2
    - name: Run tests
      run: |
        cd build
        ctest --verbose
